name: Comprobacion pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover

      - name: Lint code with PEP8
        run: pip install flake8 && flake8

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # Aquí va el comando o script para desplegar en el ambiente de producción

  review-approval:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Request review
        uses: reviewdog/action-approve@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment: "This pull request has been approved."

  notifications:
    needs: [build, deploy, review-approval]
    runs-on: ubuntu-latest

    steps:
      - name: Send notifications
        run: echo 'Send notifications to relevant parties'
